language: php
php: "5.6"
dist: trusty
cache:
  directories:
    - "node_modules"
    - "vendor"
notifications:
  email:
    - c.blahut@foreverbride.com
before_script:
  - composer install
  - npm install
script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml ./src
  - npm test